ENT.Type = "anim";
ENT.Base 		= "conflict_base";
ENT.PrintName		= "arcantrix entity augmentation"  ;
ENT.Author			= "solthar"  ;
ENT.Contact		= "solthar@gmail.com"  ;
ENT.Purpose		= "Does it really need one?"  ;
ENT.Instructions	= "Read subsection 83e, paragraph 321, line 12 in the addenedum."  ;
ENT.Spawnable			= false;
ENT.AdminSpawnable		= false;